# Generated by Django 5.0.6 on 2024-07-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Opportunity's country"),
        ),
    ]
