# Generated by Django 5.0.6 on 2024-07-08 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='stats entry unique ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('region_distribution', models.JSONField(blank=True, null=True)),
                ('overall_count', models.IntegerField(verbose_name="Opportunity'count")),
                ('new_opportunities', models.IntegerField(verbose_name="New opportunity'count")),
            ],
        ),
    ]
