# Generated by Django 5.0.6 on 2024-07-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_opportunity_country'),
        ('api', '0002_statsmodel'),
    ]

    operations = [
    ]
