# Generated by Django 5.0.6 on 2024-06-21 13:40

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Opportunity's unique ID")),
                ('title', models.CharField(max_length=200, verbose_name="Opportunity's title")),
                ('ref_number', models.CharField(blank=True, max_length=200, verbose_name="Opportunity's ref_number")),
                ('rel_score', models.IntegerField(verbose_name="Opportunity's relevance score")),
                ('country', models.CharField(max_length=100, verbose_name="Opportunity's country")),
                ('website_name', models.CharField(max_length=100, verbose_name="Opportunity's country")),
                ('size', models.IntegerField(verbose_name="Opportunity's size")),
                ('deadline', models.DateField()),
                ('website_link', models.URLField(blank=True, null=True)),
                ('page', models.JSONField(blank=True, null=True)),
                ('users', models.ManyToManyField(related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
