# Generated by Django 5.0.6 on 2024-06-20 13:51

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Opportunity's unique ID")),
                ('title', models.CharField(max_length=200, verbose_name="Opportunity's title")),
                ('org', models.CharField(max_length=200, verbose_name="Opportunity's org")),
                ('ref_number', models.CharField(max_length=200, verbose_name="Opportunity's ref_number")),
                ('rel_score', models.IntegerField(verbose_name="Opportunity's relevance score")),
                ('country', models.CharField(max_length=100, verbose_name="Opportunity's country")),
                ('website_name', models.CharField(max_length=100, verbose_name="Opportunity's country")),
                ('size', models.IntegerField(verbose_name="Opportunity's size")),
                ('deadline', models.DateField()),
                ('date_published', models.DateField()),
                ('summary', models.TextField()),
                ('website_link', models.URLField(blank=True, null=True)),
                ('intro', models.TextField()),
                ('main', models.TextField()),
                ('conclusion', models.TextField()),
                ('procedure', models.TextField()),
                ('users', models.ManyToManyField(null=True, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
