# Generated by Django 5.0.6 on 2024-06-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_opportunity_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name="Opportunity's size"),
        ),
    ]
