import React from "react";
import { Card, Typography, Box, CardContent } from "@mui/material";
import TaskAltOutlinedIcon from "@mui/icons-material/TaskAltOutlined";
import "./styles/ai.css";

function Insights() {
  return (
    <Box
      className="title-ai-insights"
      display="flex"
      justifyContent="center"
      alignSelf="flex-start"
      sx={{
        width: {
          xs: "500px",
          sm: "600px",
          lg: "720px",
          xl: "1000px",
        },
      }}
      margin="auto"
    >
      <Card
        sx={{
          margin: "30px",
          minWidth: "300px",
          width: "100%",
          backgroundColor: "inherit",
        }}
        elevation={0}
      >
        <CardContent
          sx={{
            display: "flex;",
            justifyContent: "center",
          }}
        >
          <ul className="card-list">
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                gap: {
                  xs: "8px",
                  sm: "12px",
                  lg: "24px",
                  xl: "36px",
                },
              }}
            >
              <li>
                <TaskAltOutlinedIcon style={{ color: "#6c63ff" }} />
                <Typography
                  sx={{
                    color: "#1f1650",
                    fontSize: {
                      sm: "large",
                      md: "larger",
                      lg: "x-large",
                    },
                  }}
                >
                  <span className="span">Up-to-date:</span> Stay informed with
                  the latest updates and trends, thanks toreal-time data
                  scraping and processing.
                </Typography>
              </li>
              <li>
                <TaskAltOutlinedIcon style={{ color: "#6c63ff" }} />
                <Typography
                  sx={{
                    color: "#1f1650",
                    fontSize: {
                      sm: "large",
                      md: "larger",
                      lg: "x-large",
                    },
                  }}
                >
                  <span className="span">Quality:</span> Enjoy high-quality
                  content that has been meticulously filtered and generated by
                  AI.
                </Typography>
              </li>
            </Box>
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                gap: {
                  xs: "8px",
                  sm: "12px",
                  lg: "24px",
                  xl: "36px",
                },
              }}
            >
              <li>
                <TaskAltOutlinedIcon style={{ color: "#6c63ff" }} />
                <Typography
                  sx={{
                    color: "#1f1650",
                    fontSize: {
                      sm: "large",
                      md: "larger",
                      lg: "x-large",
                    },
                  }}
                >
                  <span className="span">Relevance:</span> Experience a
                  personalized feed that adapts to your company's interests and
                  preferences.
                </Typography>
              </li>
              <li>
                <TaskAltOutlinedIcon style={{ color: "#6c63ff" }} />
                <Typography
                  sx={{
                    color: "#1f1650",
                    fontSize: {
                      sm: "large",
                      md: "larger",
                      lg: "x-large",
                    },
                  }}
                >
                  <span className="span">Efficiency:</span> Save time with
                  curated content that is both comprehensive and concise.
                </Typography>
              </li>
            </Box>
          </ul>
        </CardContent>
      </Card>
      <Box
        sx={{
          position: "absolute",
          bottom: "128px",
          width: "1000px",
          display: "flex",
          justifyContent: "center",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <Typography
          sx={{
            color: "#6c63ff",
            fontWeight: "800px",
            textTransform: "uppercase",
            fontSize: {
              sm: "large",
              md: "larger",
              lg: "x-large",
            },
          }}
        >
          Our Commitment to Privacy
        </Typography>
        <Typography
          sx={{
            fontSize: {
              sm: "0.5rem",
              md: "1rem",
              lg: "1rem",
            },
          }}
        >
          Your privacy is our priority. Our AI systems are designed to protect
          your data and ensure that any information used for personalization
        </Typography>
        <Typography
          sx={{
            fontSize: {
              sm: "0.5rem",
              md: "1rem",
              lg: "1rem",
            },
          }}
        >
          is handled securely and ethically.
        </Typography>
      </Box>
      <Box className="bg-ai-insights"></Box>
    </Box>
  );
}

export default Insights;
